"""align split models metadata

Revision ID: b7d150c74490
Revises: 9c2f3d8a1b7e
Create Date: 2026-04-11 20:49:32.708100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d150c74490'
down_revision: Union[str, None] = '9c2f3d8a1b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teacher_student_invites_token_hash', 'teacher_student_invites', type_='unique')
    op.create_index('ix_teacher_student_invite_token_hash', 'teacher_student_invites', ['token_hash'], unique=False)
    op.drop_constraint('uq_teacher_student_links_student_id', 'teacher_student_links', type_='unique')
    op.drop_index('ix_teacher_student_links_student_id', table_name='teacher_student_links')
    op.create_index(op.f('ix_teacher_student_links_student_id'), 'teacher_student_links', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_student_links_student_id'), table_name='teacher_student_links')
    op.create_index('ix_teacher_student_links_student_id', 'teacher_student_links', ['student_id'], unique=False)
    op.create_unique_constraint('uq_teacher_student_links_student_id', 'teacher_student_links', ['student_id'])
    op.drop_index('ix_teacher_student_invite_token_hash', table_name='teacher_student_invites')
    op.create_unique_constraint('uq_teacher_student_invites_token_hash', 'teacher_student_invites', ['token_hash'])
    # ### end Alembic commands ###
