OPENAPI_TAGS = [
    {"name": "system", "description": "Service health and readiness endpoints."},
    {"name": "auth", "description": "Authentication and account recovery flows."},
    {"name": "users", "description": "Current user and user management endpoints."},
    {"name": "reading", "description": "Public reading tests catalog."},
    {"name": "listening", "description": "Public listening tests catalog."},
    {"name": "writing", "description": "Public writing tests catalog."},
    {"name": "speaking", "description": "Public speaking tests catalog and realtime helpers."},
    {"name": "exams", "description": "Exam lifecycle: create, start, submit, and history."},
    {"name": "profile", "description": "User profile endpoints."},
    {"name": "progress", "description": "Progress entries and progress history."},
    {"name": "analytics", "description": "User analytics summary endpoints."},
    {"name": "dashboard", "description": "Student dashboard activity, stats, history, and links."},
    {"name": "teacher-students", "description": "Teacher-student invitation, binding, and unbinding endpoints."},
    {"name": "ai", "description": "AI module summary trigger and retrieval endpoints."},
    {"name": "ai-stream", "description": "Server-sent events stream for AI summary generation."},
    {"name": "lessons", "description": "Public lessons and categories."},
    {"name": "admin-reading", "description": "Admin CRUD for reading content."},
    {"name": "admin-listening", "description": "Admin CRUD for listening content."},
    {"name": "admin-writing", "description": "Admin CRUD for writing content."},
    {"name": "admin-exams", "description": "Admin exam review and moderation."},
    {"name": "admin-lessons", "description": "Admin CRUD for lessons."},
]
